# Generated by Django 6.0.2 on 2026-02-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('artificial_inseminator', 'Artificial Inseminator'), ('veterinarian', 'Veterinarian'), ('soil_technician', 'Soil Technician'), ('livestock_showman', 'Livestock Showman'), ('grant_officer', 'Grant Officer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_service', to=settings.AUTH_USER_MODEL)),
                ('specialist_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
