# Generated by Django 6.0.2 on 2026-02-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='specialist_provider',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='service',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('animals', 'Livestock and Veterinary'), ('soil', 'Soil and Crops'), ('machinery', 'Machinery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('soil_technician', 'Soil Technician'), ('tractor_service', 'Tractors'), ('veterinarian', 'Veterinarian'), ('livestock_showman', 'Livestock Showman')]),
        ),
    ]
