# Generated by Django 6.0.2 on 2026-02-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_specialist_provider_service_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('veterinarian', 'Veterinarian'), ('soil_technician', 'Soil Technician'), ('livestock_showman', 'Livestock Showman'), ('tractor_service', 'Tractors')]),
        ),
    ]
