# Generated by Django 6.0.2 on 2026-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('veterinarian', 'Veterinarian'), ('tractor_service', 'Tractors'), ('livestock_showman', 'Livestock Showman'), ('soil_technician', 'Soil Technician')]),
        ),
    ]
