# Generated by Django 6.0.2 on 2026-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('tractor_service', 'Tractors'), ('soil_technician', 'Soil Technician'), ('veterinarian', 'Veterinarian'), ('livestock_showman', 'Livestock Showman')]),
        ),
    ]
