# Generated by Django 6.0.2 on 2026-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('livestock_showman', 'Livestock Showman'), ('veterinarian', 'Veterinarian'), ('soil_technician', 'Soil Technician'), ('tractor_service', 'Tractors')]),
        ),
    ]
