# Generated by Django 6.0.2 on 2026-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('veterinarian', 'Veterinarian'), ('soil_technician', 'Soil Technician'), ('tractor_service', 'Tractors'), ('livestock_showman', 'Livestock Showman')]),
        ),
    ]
