# Generated by Django 6.0.2 on 2026-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('soil_technician', 'Soil Technician'), ('livestock_showman', 'Livestock Showman'), ('tractor_service', 'Tractors'), ('veterinarian', 'Veterinarian')]),
        ),
    ]
