# Generated by Django 6.0.2 on 2026-03-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('veterinarian', 'Veterinarian'), ('livestock_showman', 'Livestock Showman'), ('tractor_service', 'Tractors'), ('soil_technician', 'Soil Technician')]),
        ),
    ]
