# Generated by Django 6.0.2 on 2026-03-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('veterinarian', 'Veterinarian'), ('livestock_showman', 'Livestock Showman'), ('soil_technician', 'Soil Technician'), ('tractor_service', 'Tractors')]),
        ),
    ]
