# Generated by Django 6.0.2 on 2026-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(choices=[('tractor_service', 'Tractors'), ('soil_technician', 'Soil Technician'), ('livestock_showman', 'Livestock Showman'), ('veterinarian', 'Veterinarian')]),
        ),
    ]
