# Generated by Django 6.0.2 on 2026-03-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread_unique_thread'),
        ('orders', '0003_remove_order_produce_order_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
