# Generated by Django 6.0.2 on 2026-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('artificial_inseminator', 'Artificial Inseminator'), ('veterinarian', 'Veterinarian'), ('soil_technician', 'Soil Technician'), ('livestock_showman', 'Livestock Showman'), ('grant_officer', 'Grant Officer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('admin', 'Admin'), ('field_officer', 'Field Officer'), ('government', 'Government Official')], default='buyer', max_length=30),
        ),
    ]
