# Generated by Django 6.0.2 on 2026-02-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_sub_role_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sub_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='field',
            field=models.CharField(blank=True, choices=[('animals', 'Livestock and Veterinary'), ('soil', 'Soil and Crops'), ('machinery', 'Machinery')], max_length=30, null=True, verbose_name='fields'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('admin', 'Admin'), ('field_officer', 'Field Officer')], default='buyer', max_length=30),
        ),
    ]
