# Generated by Django 6.0.2 on 2026-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_sub_role_customuser_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('field_officer', 'Field Officer')], default='buyer', max_length=30),
        ),
    ]
