# Generated by Django 6.0.2 on 2026-02-06 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='produce image'),
        ),
    ]
