# Generated by Django 6.0.2 on 2026-02-06 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_produce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='product image'),
        ),
    ]
