# Generated by Django 6.0.2 on 2026-02-13 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(300, 'minimum price is 300')], verbose_name='price of produce'),
        ),
    ]
