# Generated by Django 6.0.2 on 2026-03-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0005_alter_produce_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='price',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProduceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='produce.produce')),
            ],
        ),
    ]
