# Generated by Django 6.0.2 on 2026-03-02 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0006_remove_produce_date_created_remove_produce_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebatch',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Minimum price per quantity is Kes 400', max_digits=10, validators=[django.core.validators.MinValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='producebatch',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter quantity above 20kgs', validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
