# Generated by Django 6.0.2 on 2026-03-02 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0007_alter_producebatch_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebatch',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter quantity above 10kgs', validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
