# Generated by Django 6.0.2 on 2026-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0008_alter_producebatch_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebatch',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('litre', 'Litres'), ('unit', 'Units')], default='kg', max_length=15),
        ),
    ]
