# Generated by Django 6.0.2 on 2026-03-16 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0009_producebatch_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebatch',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter quantity above 1 for units or 30 for litres or kilograms', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
