"""
Django settings for agri_market_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import cloudinary
import os
import dj_database_url
import urllib.parse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

cloudinary.config(
    api_key = config('CLOUDINARY_API_KEY'),
    api_secret = config('CLOUDINARY_API_SECRET'),
    cloud_name = config('CLOUDINARY_CLOUD_NAME'),
    secure = True
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cloudinary',
    'accounts',
    'produce',
    'orders',
    'reports',
    'drf_yasg',
    'services',
    'django_extensions',
    'corsheaders',
    'chat',
    'channels',
    'mpesa',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agri_market_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agri_market_project.wsgi.application'

#asgi daphne
ASGI_APPLICATION = 'agri_market_project.asgi.application'

#upstash redis
redis_url = os.environ.get("REDIS_URL")

url = urllib.parse.urlparse(redis_url)

#redis channels layers
CHANNEL_LAYERS = {
    "default":{
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(url.hostname, int(url.port), url.password)],
        },
    },
}

#mpesa
MPESA_PASSKEY= config('MPESA_PASSKEY')
MPESA_CONSUMER_KEY= config('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET=config('MPESA_CONSUMER_SECRET')
MPESA_ENVIRONMENT=config('MPESA_ENVIRONMENT')
MPESA_EXPRESS_SHORTCODE=config('MPESA_EXPRESS_SHORTCODE')
LNM_PHONE_NUMBER= config('LNM_PHONE_NUMBER')

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#          'ENGINE': 'django.db.backends.postgresql',
#          'NAME': config('DATABASE_NAME'), #add name of db created
#          'USER': config('DATABASE_USER'), #username autocreated
#          'PASSWORD': config('DATABASE_PASSWORD'),
#          'HOST': config('DATABASE_HOST'),
#          'PORT': config('PORT')
#     }
# }

#for online we use render online postgres
DATABASES = {
    'default': dj_database_url.config(
        default=config('INTERNAL_DATABASE_URL'), # fallback for local development
        conn_max_age=600,
        conn_health_checks=True
    )
}
#This logic checks if 'INTERNAL_DATABASE_URL' exists (Render). 
#If not, it falls back to local SQLite so you don't get errors on your laptop.


if os.environ.get('INTERNAL_DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('INTERNAL_DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#react integration 180226 18.15
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173"
]

#trust the origin for csrf protection
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8000"
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# to auto add slashes to say there is more after
APPEND_SLASH = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

#static
STATIC_ROOT = BASE_DIR / "staticfiles"

#CUSTOM USER MODEL
AUTH_USER_MODEL = 'accounts.CustomUser'

#login logout redirect
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = 'profile' # HOME
LOGOUT_REDIRECT_URL = 'login-list'

SWAGGER_SETTINGS = {
    'LOGOUT_URL' : '/logout/',
}


#Sessions auth lax
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_SAVE_EVERY_REQUEST = True