# Generated by Django 6.0.2 on 2026-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='reason for rejection'),
        ),
    ]
